SPOT_FOULS = [
    'Holding (Defense)', 'Illegal Contact', 'Pass Interference (Defense)', 'Targeting',
    'Horse-Collar Tackle', 'Illegal Block in the Back', 'Chop Block', 'Facemask', 'Illegal Forward Pass'
];

PENALTY_RULES = [
    # ---- PRE-SNAP OFFENSE ----
    {
        'type': 'False Start',
        'yards': 5,
        'category': 'Pre-Snap Offense',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Illegal Shift',
        'yards': 5,
        'category': 'Pre-Snap Offense',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Illegal Motion',
        'yards': 5,
        'category': 'Pre-Snap Offense',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Illegal Formation',
        'yards': 5,
        'category': 'Pre-Snap Offense',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Delay of Game',
        'yards': 5,
        'category': 'Pre-Snap Offense',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },

    # ---- PRE-SNAP DEFENSE ----
    {
        'type': 'Offside',
        'yards': 5,
        'category': 'Pre-Snap Defense',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Encroachment',
        'yards': 5,
        'category': 'Pre-Snap Defense',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Neutral Zone Infraction',
        'yards': 5,
        'category': 'Pre-Snap Defense',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Disconcerting Signals',
        'yards': 5,
        'category': 'Pre-Snap Defense',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },

    # ---- GAMEPLAY ----
    {
        'type': 'Holding (Offense)',
        'yards': 10,
        'category': 'Gameplay',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Holding (Defense)',
        'yards': 10,
        'category': 'Gameplay',
        'spot_foul': True,
        'loss_of_down': False,
        'automatic_first_down': True,
    },
    {
        'type': 'Illegal Contact',
        'yards': 5,
        'category': 'Gameplay',
        'spot_foul': True,
        'loss_of_down': False,
        'automatic_first_down': True,
    },
    {
        'type': 'Pass Interference (Defense)',
        'yards': 15,
        'category': 'Gameplay',
        'spot_foul': True,
        'loss_of_down': False,
        'automatic_first_down': True,
    },
    {
        'type': 'Pass Interference (Offense)',
        'yards': 15,
        'category': 'Gameplay',
        'spot_foul': False,
        'loss_of_down': True,
        'automatic_first_down': False,
    },
    {
        'type': 'Ineligible Receiver Downfield',
        'yards': 5,
        'category': 'Gameplay',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Blocking Below the Waist',
        'yards': 15,
        'category': 'Gameplay',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Targeting',
        'yards': 15,
        'category': 'Gameplay',
        'spot_foul': True,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Roughing the Passer',
        'yards': 15,
        'category': 'Gameplay',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': True,
    },
    {
        'type': 'Roughing the Kicker',
        'yards': 15,
        'category': 'Gameplay',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': True,
    },
    {
        'type': 'Unsportsmanlike Conduct',
        'yards': 15,
        'category': 'Gameplay',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Horse-Collar Tackle',
        'yards': 15,
        'category': 'Gameplay',
        'spot_foul': True,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Illegal Block in the Back',
        'yards': 10,
        'category': 'Gameplay',
        'spot_foul': True,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Chop Block',
        'yards': 15,
        'category': 'Gameplay',
        'spot_foul': True,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Facemask',
        'yards': 15,
        'category': 'Gameplay',
        'spot_foul': True,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Illegal Forward Pass',
        'yards': 5,
        'category': 'Gameplay',
        'spot_foul': True,
        'loss_of_down': True,
        'automatic_first_down': False,
    },

    # ---- SPECIAL/ADMIN ----
    {
        'type': 'Feigning Injury',
        'yards': 15,
        'category': 'Special/Admin',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Illegal Substitution',
        'yards': 5,
        'category': 'Special/Admin',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Illegal Signal Devices',
        'yards': 15,
        'category': 'Special/Admin',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Illegal Scrimmage Formation (Kicks)',
        'yards': 5,
        'category': 'Special/Admin',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Game Administration Interference',
        'yards': 5,
        'category': 'Special/Admin',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
    {
        'type': 'Illegal Celebration',
        'yards': 15,
        'category': 'Special/Admin',
        'spot_foul': False,
        'loss_of_down': False,
        'automatic_first_down': False,
    },
]
